import {
  faBasketShopping,
  faCity,
  faFerry,
  faFilm,
  faHippo,
  faHouse,
  faIceCream,
  faLandmark,
  faMapLocation,
  faMountain,
  faMugHot,
  faPersonBiking,
  faPersonHiking,
  faPersonRunning,
  faPersonWalking,
  faShop,
  faTree,
  faUmbrellaBeach,
  faUtensils,
} from "@fortawesome/free-solid-svg-icons";

export const locationTypeIcons = {
  city: faCity,
  neighborhood: faHouse,
  park: faTree,
};

export const activityIcons = {
  coffee: faMugHot,
  run: faPersonRunning,
  restaurant: faUtensils,
  walk: faPersonWalking,
  bikeRide: faPersonBiking,
  zoo: faHippo,
  safariPark: faPersonWalking,
  brewery: faPersonWalking,
  drink: faPersonWalking,
  museum: faPersonWalking,
  beachDay: faUmbrellaBeach,
  beachWalk: faUmbrellaBeach,
  hike: faPersonHiking,
  mountain: faMountain,
  movie: faFilm,
  historic: faLandmark,
  boatRide: faFerry,
  guidedTour: faMapLocation,
  picnic: faBasketShopping,
  iceCream: faIceCream,
  shopping: faShop,
};
